### PR TITLE
(+): upgraded the project to the latest stable Cocos2D 2.0 and converted the project to ARC.

### PR DESCRIPTION
**Pull request by Panajev**

### CODE REVIEW

**Comment by sneakyness** [comment]
Omg everybody is going to love you

**Comment by Panajev** [comment]
Thank you for your words.

There is a further change I made to the patch you merged, sorry for it, but it is a quite small change (which you might already have performed, it relates to making sure we think in points throughout the API):

Inside ColoredCircleSprite.m:

``` objective-c
-       float j = radius_ * [[CCDirector sharedDirector] contentScaleFactor] * cosf(theta) + position_.x;
-       float k = radius_ * [[CCDirector sharedDirector] contentScaleFactor] * sinf(theta) + position_.y;
+       float j = radius_ * cosf(theta) + position_.x;
+       float k = radius_ * sinf(theta) + position_.y;
```

Basically, the ccDrawSolid methods expect a radius in points and not in pixels, so with this on we had two problems: objects in the HelloWorldDemo would appear twice as big when played on Retina displays and there was a problem with the distance the joystick thumb could travel (not the same as the non Retina version) and the hit area of the button which appears off screen in the demo.

BTW, I am referring to the solid shapes and not objects built with textures.

Here is the commit I am referring to: https://github.com/Panajev/SneakyInput/commit/987d25d2970cfff390b50bb814bd2f6c267f8f22

Could you integrate this change as well?

Thank you and sorry for missing this bit earlier.

**Comment by ThePragmaticArt** [comment]
This hasn't been updated for Cocos2d 2.1 and does not support proper implementation for both ARC and proper apple standards (many instance variables use a suffix of _ rather a prefix). There are over 21 warnings with the project from the get go not to mention pure errors I had to dig in and correct manually.

**Comment by sneakyness** [comment]
@thegamingart pull requests welcome ^_^

**Pull request merged**
